[Modular] Cryostasis
Jolly-66/JollyStation pull request #22
Opened 2021-02-07 02:02 UTC by unit0016

## About The Pull Request
Adds Cryo sleepers to the game, which let people who need to leave.. leave, instead of just suiciding or SSDing. Also reopens job slots.

## Why It's Good For The Game
suicide bad mmmkay

## Changelog
:cl:
add: Cryosleep.
/:cl:

2021-02-07 09:37 UTC, Jolly-66 commented
Can you document where these will be in the maps?

2021-02-07 20:09 UTC, MrMelbert reviewed
i don't know how it's _supposed_ to work but it looks fine

2021-02-07 20:09 UTC, MrMelbert commented on jollystation_modules/code/game/machinery/cryopod.dm
> +		if(mob_occupant && mob_occupant.stat != DEAD)
```suggestion
		if(mob_occupant?.stat != DEAD)
```

2021-02-07 20:09 UTC, MrMelbert commented on jollystation_modules/code/game/machinery/cryopod.dm
> +			to_chat(user, "<span class='danger'>You can't put [target] into [src]. They're online.</span>")
"They're online." lol

2021-02-07 20:09 UTC, MrMelbert commented on jollystation_modules/code/game/machinery/cryopod.dm
> +			log_admin("<span class='notice'>[key_name(target)] entered a stasis pod.</span>")
`log_admin` seems like a weird place to put this, compared to `log_game` or something

2021-02-07 20:14 UTC, MrMelbert requested changes
also merge conflicts

2021-02-07 21:34 UTC, unit0016 commented on jollystation_modules/code/game/machinery/cryopod.dm
> +			to_chat(user, "<span class='danger'>You can't put [target] into [src]. They're online.</span>")
It's talking about a borg. Seems fine to me.

2021-02-08 02:25 UTC, MrMelbert approved these changes
some improvements could still be made but nothing major so sure why not

2021-02-08 02:26 UTC, merged

2021-02-08 02:27 UTC, MrMelbert commented on jollystation_modules/code/game/machinery/cryopod.dm
> +	var/time_till_despawn = 15 * 600 // This is reduced by 90% if a player manually enters cryo
for future reference we have macros for time to use
`15 MINUTES` instead of `15 * 600`