[Modular] AESTHETICS
Jolly-66/JollyStation pull request #26
Opened 2021-02-07 19:59 UTC by unit0016

## About The Pull Request
removes soul
## Before
![image](https://user-images.githubusercontent.com/50649185/107157939-f562e300-6954-11eb-9d0f-afe59986e31e.png)
![image](https://user-images.githubusercontent.com/50649185/107157947-001d7800-6955-11eb-90d1-a80e0390ba56.png)
![image](https://user-images.githubusercontent.com/50649185/107157956-03b0ff00-6955-11eb-82d2-78de36585d5d.png)
## After
![image](https://user-images.githubusercontent.com/50649185/107157967-0ca1d080-6955-11eb-8cb0-00f3e256c27b.png)
![image](https://user-images.githubusercontent.com/50649185/107157969-0f042a80-6955-11eb-8226-b3e1cd8575ea.png)
![image](https://user-images.githubusercontent.com/50649185/107157970-10cdee00-6955-11eb-9167-fd4cbb208368.png)

## Why It's Good For The Game
fuck soul

## Changelog
:cl:
del: soul
add: aesthetic
/:cl:

2021-02-07 20:23 UTC, MrMelbert requested changes
this should probably be put up to a poll to see which style people prefer

2021-02-07 20:23 UTC, MrMelbert commented on jollystation_modules/modules/aesthetics/computer/code/computer.dm
> +	return soundin
proc should probably be renamed, with a comment to credit the origin

2021-02-07 20:23 UTC, MrMelbert commented on jollystation_modules/modules/aesthetics/floors/code/floors.dm
> +/turf/open/floor/plasteel/kitchen
Plasteel types were repathed to iron as of feburary the 6th on tg main, so all plasteel tiles will break in the future guaranteed

2021-02-07 20:23 UTC, MrMelbert commented on jollystation_modules/modules/aesthetics/readme.md
> +https://github.com/Skyrat-SS13/Skyrat-tg/pull/1245
this uses skyrat's method of modularization instead of the one I adapted, which for this many files actually makes sense so i'm okay with it

2021-02-07 20:30 UTC, Jolly-66 commented
i personally don't vibe with the APCs/air alarms/fire alarms, wall buttons and the SM

also im assuming full tile windows were touched too but i don't vibe either

2021-02-07 20:36 UTC, unit0016 commented on jollystation_modules/modules/aesthetics/floors/code/floors.dm
> +/turf/open/floor/plasteel/kitchen
good point, this is all excess anyways so I can nuke it.

2021-02-08 15:48 UTC, Jolly-66 commented
the general consensus is still pretty mixed (6:4, i voted twice to put the reactions there), so i'm going to close this

if in the future we want to come back at this we can, but it would appear art style conflicts are going to be the main concern and i don't blame them. the sprites are gorgeous but against some of TGs drab sprites, its like putting the mona lisa next to some coloring book page pinned to the wall, and they didn't color in between the lines either

i personally may want something out of here if i can think of a justifiable reason to, without trying to conflict with general art style. we're in no position to try and resprite the entire game, even if we were to pull from different codebases, it would still be a task.

2021-02-08 15:48 UTC, closed without merging