Creates a healthy alternative for breakfast!
Jolly-66/JollyStation pull request #43
Opened 2021-03-04 22:49 UTC by Wallemations

## About The Pull Request

Creates a delicious breakfast with just 650 calories! Perfect for anyone hoping for a delicious meal!

## Why It's Good For The Game
![healthy_diet](https://user-images.githubusercontent.com/66052067/110041341-f697ed80-7d11-11eb-86e0-01928ff57dce.jpg)

## Changelog
:cl: Wallem
add: Upon Nanotrasen's dietitians releasing their recommended protein intake data, a new egg-based meal has been added to the station's menus!
/:cl:

2021-03-04 22:59 UTC, Jolly-66 commented
currently working on an upstream merge.
melbert don't review this yet until the repo is updated

2021-03-05 06:43 UTC, MrMelbert commented
![image](https://user-images.githubusercontent.com/51863163/110077423-b48b9d80-7d4b-11eb-935b-dbfccaf940e7.png)
reeeeeeee
https://github.com/Jolly-66/JollyStation/blob/master/jollystation_modules/README.md

2021-03-05 21:43 UTC, Jolly-66 commented
also i wanna see the sprites, so whenever you can either comment them or put them in your main pr

2021-03-05 21:56 UTC, Jolly-66 requested changes
> ![image](https://user-images.githubusercontent.com/51863163/110077423-b48b9d80-7d4b-11eb-935b-dbfccaf940e7.png)
> reeeeeeee
> https://github.com/Jolly-66/JollyStation/blob/master/jollystation_modules/README.md

melbert did it before i felt like it
modularize the dmi

2021-03-05 21:56 UTC, Jolly-66 commented on code/game/objects/items/food/egg.dm
> +	list_reagents = list(/datum/reagent/consumable/nutriment/protein = 108, /datum/reagent/consumable/nutriment/vitamin = 36) //520 kcals from protein in a diet of 650 kcals
```suggestion
/obj/item/food/balancedegg
	name = "balanced breakfast"
	desc = "Only 650 calories, perfect for any dieting station members!"
	icon_state = "balancedegg"
	trash_type = /obj/item/trash/plate
	list_reagents = list(/datum/reagent/consumable/nutriment/protein = 108, /datum/reagent/consumable/nutriment/vitamin = 36)
```

don't need these comments, they're just a meme only the 3 of us will see

2021-03-05 21:56 UTC, Jolly-66 commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_egg.dm
> +		/obj/item/reagent_containers/food/snacks/boiledegg = 36, //SPECIFICALLY Hard boiled eggs
```suggestion
		/obj/item/reagent_containers/food/snacks/boiledegg = 36, 
```

again, meme comment no one else will see

2021-03-05 22:41 UTC, Wallemations commented
> > ![image](https://user-images.githubusercontent.com/51863163/110077423-b48b9d80-7d4b-11eb-935b-dbfccaf940e7.png)
> > reeeeeeee
> > https://github.com/Jolly-66/JollyStation/blob/master/jollystation_modules/README.md
> 
> melbert did it before i felt like it
> modularize the dmi

Ah. Fun. I'll remember to do that.

2021-03-10 15:12 UTC, Jolly-66 commented
since melbert converted this to a draft, the merge conflicts are hidden, but they were all 3 files

2021-03-11 19:40 UTC, Jolly-66 commented
also i just want to say i'm personally not as huge fan of the sprite, it just looks like a ball of eggs
i get this is mostly a joke, but i highly doubt someone would go out of there way to try and make this, considering it needs a metric fuckton of eggs that could be put elsewhere, and would require a botanist to grow egg-plants to help offset the now missing eggs

2021-03-12 03:25 UTC, Jolly-66 commented
wallems going to come back with a different idea

2021-03-12 03:25 UTC, closed without merging